FROM openjdk:8
EXPOSE 8085
ADD /target/user-authentication-service-0.0.1-SNAPSHOT.jar user-authentication-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","user-authentication-service-0.0.1-SNAPSHOT.jar"]